Online Book Store/config/routes.rb
Rails.application.routes.draw do
  

  get 'access/new'
  get 'access/create'
  get 'access/destroy' 

  get 'admin/index'
  get 'login', to: 'access#new'
  post 'access/new', to: 'access#create'
  delete 'logout', to: 'access#destroy'

  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'shopper/index'

  resources :products
  root "shopper#index", as: 'root'
  get '/shopper', to: redirect('shopper/index')
  get '/admin', to: redirect('admin/index')

  get 'public/home', to: redirect('/home.html')
  get 'public/questions', to: redirect('/questions.html')
  get 'public/contact', to: redirect('/contact.html')
  get 'public/news', to: redirect('/news.html')

  
  #get 'products/questions'
  #get 'products/news'
  #get 'products/contact'
  #get 'admin', to:'admin#index'
  #get 'shopper', to: 'shopper#index'
  
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Online Book Store/app/models/cart.rb
class Cart < ApplicationRecord
	has_many :lineitems, dependent: :destroy

	def add_item( product_id)
		current_item = lineitems.find_by(product_id: product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = lineitems.build(product_id: product_id)
		end
		current_item
	end
	
	def total_price
		lineitems.to_a.sum {|item| item.total_price}
	end
end

Online Book Store/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id] 
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to shopper_url, notice: 'Your shopping cart is empty.' } 
      format.json { head :no_content }
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
  end

Online Book Store/app/helpers/carts_helper.rb
module CartsHelper
end

Online Book Store/app/views/carts/_cart.html.erb
<h3>Items in your shopping cart</h3>
<table>
	<% @cart.lineitems.each do |item|%>
	<tr>
		<td><%= item.quantity %></td>
		<td><%=item.product.name %></td>
		<td class='item_price'><%=number_to_currency(item.product.price) %></td>
	</tr>
	<%end%>
	<tr class='total_line'>
		<td colspan = "2">Total</td>
		<td class='total_cell'><%=number_to_currency(@cart.total_price)%></td>
	</tr>
</table>
<%= button_to 'Check Out', new_order_path, method: :get %>
<%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: 'Are you sure you want to empty your cart?'} %>

Online Book Store/app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Online Book Store/app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<br><br>
<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

Online Book Store/app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

Online Book Store/app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

Online Book Store/app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
<%= render @cart%>