Online Book Store/config/routes.rb
Rails.application.routes.draw do
  

  get 'access/new'
  get 'access/create'
  get 'access/destroy' 

  get 'admin/index'
  get 'login', to: 'access#new'
  post 'access/new', to: 'access#create'
  delete 'logout', to: 'access#destroy'

  resources :users
  resources :orders
  resources :lineitems
  resources :carts

  get 'shopper/index'

  resources :products
  root "shopper#index", as: 'root'
  get '/shopper', to: redirect('shopper/index')
  get '/admin', to: redirect('admin/index')

  get 'public/home', to: redirect('/home.html')
  get 'public/questions', to: redirect('/questions.html')
  get 'public/contact', to: redirect('/contact.html')
  get 'public/news', to: redirect('/news.html')

  
  #get 'products/questions'
  #get 'products/news'
  #get 'products/contact'
  #get 'admin', to:'admin#index'
  #get 'shopper', to: 'shopper#index'
  
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Online Book Store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Book Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class='<%= controller.controller_name %>'>

  <div id="banner">
    <%= @page_title || "MY ONLINE BOOKSTORE" %>
    <%= image_tag("logo.png", size: "60x50") %>

    <% if session[:user_id] %>
    <div id="login_button"><%= link_to 'LOGOUT', logout_path, method: :delete %></div>
    <% else %>
    <div id="login_button"><%= link_to 'LOGIN', login_path %></div>
    <% end %> 
  </div>

  <div id="columns">
    <div id="side">
      <h1><b>My Cart</b></h1>
      <div id="cart">
        <%= render @cart %>
      </div>

      <ul>
        <% if session[:user_id] %>
        <li><a href="/admin/index">Home</a></li>
        <% else %>
        <li><a href="/shopper/index">Home</a></li>
        <% end %> 
        <li><a href="/public/questions.html">Questions</a></li>
        <li><a href="/public/news.html">News</a></li>
        <li><a href="/public/contact.html">Contact</a></li>
      </ul>

      <% if session[:user_id] %>
      <br>
      <h1>Admin Control</h1>
      <ul>
        <li><%= link_to 'Orders', orders_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
      <% end %> 

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>